AWSTemplateFormatVersion: "2010-09-09" 
Parameters:
  ECRRepositoryName:
    Type: String
    Description: "Name for the ECR repository"
    Default: "processing-ecr-repo"
  AWSAccountId:
    Type: String
    Description: "AWS Account id"
    Default: "955247798604"    
  AWSUserName:
    Type: String
    Description: "Servive user name"
    Default: "app-dev"

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RepositoryName: !Ref ECRRepositoryName
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement: [
          {
              "Sid": "AllowPushPull",
              "Effect": "Allow",
              "Principal": {
                  "AWS": [
                     !Sub arn:aws:iam::${AWSAccountId}:user/${AWSUserName},
                  ]
              },
              "Action": [
                  "ecr:BatchGetImage",
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:CompleteLayerUpload",
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:InitiateLayerUpload",
                  "ecr:PutImage",
                  "ecr:UploadLayerPart"
              ]
          }
        ]