AWSTemplateFormatVersion: "2010-09-09" 
Parametrs:
  ECRRepositoryName:
    Type: String
    Description: "Name for the ECR repository"
    Default: "processing-erc-repo"

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RepositoryName: !Ref ECRRepositoryName

  ECRBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ECRRepositoryName}-build"
      Description: "CodeBuild project to build and publish Docker image"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - $(aws ecr get-login --no-include-email --region ${AWS::Region})
            build:
              commands:
                - echo Building the Docker image...
                - docker build -t ${ECRRepositoryName}:latest .
            post_build:
              commands:
                - echo Tagging the Docker image...
                - docker tag ${ECRRepositoryName}:latest ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}:latest
                - echo Publishing the Docker image to Amazon ECR...
                - docker push ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}:latest
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
      ServiceRole: !GetAtt ECRBuildProjectRole.Arn
      
  ECRBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ECRRepositoryName}-build-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess