AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      BucketName: "image-landing-bucket"
  MySQSQueue:
    Type: "AWS::SQS::Queue"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      QueueName: "image-processing-queue"
  MyECRRepository:
    Type: AWS::ECR::Repository
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      RepositoryName: processing-erc-repo