AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "image-landing-bucket"
  MySQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "image-processing-queue"