name: Clean up AWS Resources

on:
  workflow_dispatch:

jobs:
  delete-stack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
        aws-region: us-east-1 # change this to your desired region

    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack --stack-name resourcese-allocation-stack
        aws cloudformation delete-stack --stack-name lambda-deployment-stack
